# Generated by Django 4.2.7 on 2023-11-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_note"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Note",
        ),
        migrations.AddField(
            model_name="task",
            name="note",
            field=models.TextField(null=True),
        ),
    ]
